name: Auto Sync Data

on:
  schedule:
    # 测试阶段：每10分钟执行一次
    - cron: '*/10 * * * *'
    # 测试正常后，取消上面的注释，使用下面的配置（每小时执行一次）
    # - cron: '0 * * * *'

jobs:
  auto-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Fetch JSON data
        run: |
          curl https://api.dabing.one?whiteboard_id=b761781d20fb60d8ca9cb140d6cbf997c1ffc7c25d964e770dadf3f34af5fd62 > src/resources/data.json

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Save JSON data to repository
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add src/resources/data.json
          git commit -m "Auto update data.json [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

