name: Auto Sync Data

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    # 每30分钟执行一次（在每小时的 0 分和 30 分触发）
    - cron: '*/30 * * * *'

jobs:
  auto-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入仓库内容
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Fetch JSON data
        run: |
          curl https://api.dabing.one?whiteboard_id=b761781d20fb60d8ca9cb140d6cbf997c1ffc7c25d964e770dadf3f34af5fd62 > src/resources/data.json

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Save JSON data to repository
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add src/resources/data.json
          git commit -m "Auto update data.json [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

